### ISSUE TITLE
GetUserIDs method results in 400 Bad Request error

### ISSUE THREAD

**Issue by crayolakat** [KaushalKhamar/SPPeoplePicker#1]
**Describe the bug**
When attempting to run the GetUserIDs method on a People Picker field, the result is a 400 Bad error response.

**To Reproduce**
1. Enter a name in a People Picker field
2. Open Developer tools and run GetUserIDs on the People Picker field
3. See error

**Expected behavior**
An array of user IDs will be returned

**Screenshots**
![Capture](https://user-images.githubusercontent.com/9382984/85610871-67382780-b625-11ea-8b67-d76bb56730df.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 83.0.4103.116

**Additional context**
jQuery version 1.11.1

**Comment by KaushalKhamar** [comment]
Get latest code. It will resolved issue.
